# Configuration all env mail
ADDRESS:    'smtp.gmail.com'
PORT:       '587'
DOMAIN:     'gmail.com'
USER_NAME:  ''
PASSWORD:   ''

# From email
FROM_MAIL: ''

# Paths and URls
UPLOAD_HOST:    'http://cnd1.localtest.me:3000/'
SFTP_FOLDER: ''
SFTP_HOST: ''
SFTP_USER: ''
SFTP_PASSWORD: ''
